version: '3.1'
services:
  api:
    image: 'simple-chat'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/simpleChat
      - SPRING_DATASOURCE_USERNAME=simpleChatUser
      - SPRING_DATASOURCE_PASSWORD=chatPassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    volumes:
      - ./docker:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_NAME=simpleChat
      - APP_DB_USER=simpleChatUser
      - APP_DB_PASS=chatPassword
