spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/simplechat?stringtype=unspecified
    port: 5434
    username: postgres
    password: postgres